{% set _version_match = load_file_regex(
  load_file="linear_operator/version.py",
  regex_pattern="__version__ = version = '(.+)'"
) %}
{% set version = _version_match[1] %}

package:
  name: linear_operator
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: "$PYTHON ./setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python>=3.8

  run:
    - python>=3.8
    - pytorch>=1.11
    - scipy
    - jaxtyping==0.2.19

test:
  imports:
    - linear_operator
    - linear_operator.functions
    - linear_operator.operators
    - linear_operator.utils

about:
  home: https://gpytorch.ai
  license: MIT
  license_file: LICENSE
  summary: A linear operator implementation, primarily designed for finite-dimensional positive definite operators (i.e. kernel matrices).
  doc_url: https://linear_operator.readthedocs.io/en/stable/
  dev_url: https://github.com/cornellius-gp/linear_operator
