# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push to Main CI

on:
  push:
    branches: [ main ]

jobs:
  run_linter:
    uses: ./.github/workflows/run_linter.yml

  run_test_suite:
    uses: ./.github/workflows/run_type_checked_test_suite.yml
